/* AI-lederscreener — datagrunnlag
 *
 * Skårer (1–10) er kvalitative vurderinger basert på offentlig tilgjengelig
 * informasjon (årsrapporter, investorpresentasjoner, kapitalmarkedsdager,
 * pressemeldinger og bransjeindekser) per 2026. De er et utgangspunkt for
 * videre analyse, ikke investeringsråd. Oppdater skår og begrunnelse her.
 *
 * Rekkefølge i s (skår) og r (begrunnelse):
 *   0 strat  — Strategi & ledelse
 *   1 data   — Data-vollgrav
 *   2 dig    — Digitale agenter i drift
 *   3 phys   — Fysisk AI & autonomi
 *   4 talent — Talent & teknologistakk
 *   5 impact — Dokumentert økonomisk effekt
 *   6 cap    — Omstillingskapasitet (finansiell)
 */

window.METRICS = [
  {
    key: "strat",
    name: "Strategi & ledelse",
    short: "Strategi",
    q: "Er AI forankret hos toppledelsen og i kapitalallokeringen?",
    looks: [
      "AI er eksplisitt del av konsernstrategien og finansielle mål",
      "Egen AI-/dataleder i konsernledelsen (CAIO/CDAO)",
      "Organisasjonen bygges om rundt AI – ikke bare piloter",
      "Konkrete, offentlige mål for agenter og automatisering"
    ],
    anchors: ["Vage utsagn, ingen eierskap i ledelsen", "Pilotprogrammer og innovasjonsenhet", "Selskapet reorganiseres rundt AI, styret måler det"]
  },
  {
    key: "data",
    name: "Data-vollgrav",
    short: "Data",
    q: "Har selskapet unike, proprietære data som forbedres med bruk?",
    looks: [
      "Volum og bredde av egne kunde-, drifts- eller sensordata",
      "Data som konkurrenter ikke kan kjøpe eller kopiere",
      "Tilbakekoblingssløyfer: mer bruk → bedre modeller → mer bruk",
      "Datainfrastruktur i skyen, samlet og styrt"
    ],
    anchors: ["Fragmenterte data i siloer", "Gode data, men lite unike", "Unik, voksende datastrøm med innebygd tilbakekobling"]
  },
  {
    key: "dig",
    name: "Digitale agenter i drift",
    short: "Dig. agenter",
    q: "Utfører AI-agenter reelt arbeid i produksjon i dag?",
    looks: [
      "Agenter i kundeservice, saksbehandling, back-office og koding",
      "Andel ansatte med daglig tilgang til GenAI-verktøy",
      "Antall use cases i produksjon (ikke piloter)",
      "Agenter som resonnerer og utfører flerstegsoppgaver selvstendig"
    ],
    anchors: ["Chatbot og enkeltstående piloter", "Bred assistent-utrulling til ansatte", "Multi-agentsystemer utfører kjerneprosesser"]
  },
  {
    key: "phys",
    name: "Fysisk AI & autonomi",
    short: "Fysisk AI",
    q: "Bruker selskapet roboter, autonomi og sensorer i den fysiske verden?",
    looks: [
      "Roboter i lager, fabrikk, lab eller felt",
      "Autonome kjøretøy, maskiner eller fartøy",
      "Digitale tvillinger og fjernstyrte/ubemannede operasjoner",
      "Egen utvikling vs. innkjøpt automasjon"
    ],
    anchors: ["Ingen/lite fysisk automasjon", "Innkjøpt automasjon i deler av driften", "Egenutviklet autonomi i stor skala"],
    note: "Vektes etter hvor fysisk bransjen er (se «fysisk eksponering» per industri)."
  },
  {
    key: "talent",
    name: "Talent & teknologistakk",
    short: "Talent",
    q: "Kan selskapet bygge selv – eller bare kjøpe?",
    looks: [
      "Antall AI-/ML-ingeniører og forskere",
      "Egen plattform, egne modeller eller egen compute",
      "Strategiske partnerskap med ledende AI-labber/chipleverandører",
      "Teknologibudsjett som andel av omsetning"
    ],
    anchors: ["Avhengig av konsulenter", "Solid intern kapasitet + partnere", "Bygger egne modeller/plattformer i verdensklasse"]
  },
  {
    key: "impact",
    name: "Dokumentert økonomisk effekt",
    short: "Effekt",
    q: "Vises AI i tallene – kostnader, inntekter eller marginer?",
    looks: [
      "Rapportert verdi/ROI fra AI i kroner og øre",
      "Kostnadsreduksjon, færre manuelle årsverk per enhet",
      "Nye AI-baserte inntektsstrømmer",
      "Marginforbedring vs. konkurrenter"
    ],
    anchors: ["Ingen målbare tall", "Produktivitetstall og anekdoter", "Revisjonsnære tall med vesentlig resultateffekt"]
  },
  {
    key: "cap",
    name: "Omstillingskapasitet",
    short: "Kapasitet",
    q: "Har selskapet finansiell styrke til å investere seg gjennom omstillingen?",
    looks: [
      "Fri kontantstrøm og balanse",
      "Teknologi-/capex-budsjett i absolutt størrelse",
      "Markedsposisjon som tåler investeringsfaser",
      "Fravær av akutte kriser som stjeler ledelsens fokus"
    ],
    anchors: ["Presset balanse eller krise", "Solid, men begrenset handlingsrom", "Kan investere titalls milliarder uten å svekke seg"]
  }
];

/* Pilarer som brukes i totalskår. «exec» = digitale agenter og fysisk AI,
 * blandet etter industriens fysiske eksponering p:  exec = (1-p)*dig + p*phys */
window.PILLARS = [
  { key: "strat",  name: "Strategi & ledelse",     w: 10 },
  { key: "data",   name: "Data-vollgrav",          w: 20 },
  { key: "exec",   name: "Agent-utførelse",        w: 35 },
  { key: "talent", name: "Talent & stakk",         w: 10 },
  { key: "impact", name: "Dokumentert effekt",     w: 15 },
  { key: "cap",    name: "Omstillingskapasitet",   w: 10 }
];

window.INDUSTRIES = [
  { id: "bank", name: "Bank & finans", icon: "🏦", p: 0.10,
    why: "Kunnskapsarbeid, dokumenter og regler – nesten alt kan utføres av digitale agenter. Vinnerne får strukturelt lavere kostnad per kunde." },
  { id: "ins", name: "Forsikring", icon: "🛡️", p: 0.15,
    why: "Prising, underwriting og skadeoppgjør er datatunge beslutningskjeder. Agenter kan håndtere enkle krav ende-til-ende; datafortrinn gir bedre risikoprising." },
  { id: "health", name: "Helse & farma", icon: "🧬", p: 0.35,
    why: "AI kan korte ned tid og kostnad i legemiddelutvikling, automatisere labber og klinisk dokumentasjon. Kirurgiske roboter og diagnostikk er fysisk AI." },
  { id: "energy", name: "Energi & kraft", icon: "⚡", p: 0.55,
    why: "Ubemannede plattformer, prediktivt vedlikehold, seismikk og nettstyring. AI-boomen øker også etterspørselen etter kraft." },
  { id: "auto", name: "Bil & mobilitet", icon: "🚗", p: 0.85,
    why: "Bilen blir en robot: selvkjøring, robotaxi og humanoider bygger på samme teknologi. Flåtedata er den viktigste vollgraven." },
  { id: "ind", name: "Industri & maskiner", icon: "🏭", p: 0.80,
    why: "Fabrikker, anleggsmaskiner og landbruk automatiseres. Leverandørene av automasjon og digitale tvillinger blir operativsystemet for fysisk AI." },
  { id: "retail", name: "Varehandel & e-handel", icon: "🛒", p: 0.45,
    why: "Agentisk handel (AI som handler for kunden), robotiserte lagre og AI-drevet sortiment og prising endrer marginene." },
  { id: "logistics", name: "Transport & logistikk", icon: "📦", p: 0.70,
    why: "Ruteoptimalisering, robotisert sortering, autonome lastebiler og digitale fraktagenter. Store fysiske nettverk gir dataovertak." },
  { id: "telecom", name: "Telekom & media", icon: "📡", p: 0.30,
    why: "Nettverket blir AI-infrastruktur (AI-RAN, edge, AI-fabrikker). Kundeservice og nettdrift er tidlige agent-områder." },
  { id: "travel", name: "Reiseliv & hotell", icon: "✈️", p: 0.15,
    why: "AI-reiseagenter kan planlegge og booke hele reiser. Plattformene som eier kunderelasjonen og lagerdata vinner – eller blir forbigått av AI-assistenter." }
];

/* n = navn, t = ticker, x = børs/land, i = industri, s = skår, r = begrunnelse,
 * th = investeringstese, rk = nøkkelrisiko */
window.COMPANIES = [
  /* ---------------- BANK & FINANS ---------------- */
  { n: "JPMorgan Chase", t: "JPM", x: "NYSE · USA", i: "bank", s: [10,10,9,3,10,9,10],
    r: ["Toppledelsen omtaler AI som like transformativt som internett; data- og AI-ansvar sitter i operativ komité.",
        "Transaksjonsdata fra titalls millioner amerikanske kunder pluss global markeds- og betalingsflyt.",
        "Intern LLM Suite rullet ut til ~200 000 ansatte; agentiske verktøy i investeringsbank, drift og koding.",
        "Lite relevant for bransjen; noe automatisering i filialer og kontanthåndtering.",
        "Teknologibudsjett rundt USD 18 mrd årlig, tusenvis av AI/ML-ansatte og egen forskningsenhet.",
        "Kommuniserer AI-verdi i milliard-USD-klassen og målbar produktivitet i drift og service.",
        "Bransjens sterkeste inntjening og balanse gir uovertruffen investeringsevne."],
    th: "Global referanse for AI i bank – skala, data og gjennomføring samtidig.",
    rk: "Regulering og modellrisiko; størrelse kan bremse radikal omorganisering." },
  { n: "Capital One", t: "COF", x: "NYSE · USA", i: "bank", s: [9,9,8,1,9,7,7],
    r: ["Bygget som teknologiselskap; fullt skybasert og modelldrevet kreditt i flere tiår.",
        "Rike kort- og forbruksdata, ytterligere styrket av oppkjøpet av Discover og dets betalingsnettverk.",
        "Multi-agentsystemet Chat Concierge i produksjon mot kunder; bred intern agentutvikling.",
        "Ingen vesentlig fysisk eksponering.",
        "Stor egen ingeniørstab og AI-forskning; rangeres helt i toppen av uavhengige bank-AI-indekser.",
        "Effekt synlig i kredittap og effektivitet, men mindre tallfestet offentlig.",
        "Solid, men mindre finansiell muskel enn de største globale bankene; integrasjon av Discover pågår."],
    th: "Den mest «tech-native» storbanken – AI er bygget inn i kreditt-DNAet.",
    rk: "Kredittsyklus og integrasjonsrisiko etter Discover." },
  { n: "DBS Group", t: "D05", x: "SGX · Singapore", i: "bank", s: [9,8,8,1,8,9,7],
    r: ["Langvarig digital transformasjon drevet fra toppen; AI-mål forankret i styret.",
        "Sterke kundedata i Singapore og Sørøst-Asia, men mindre global skala.",
        "Hundrevis av AI-modeller i produksjon og GenAI-assistenter for ansatte og kunder.",
        "Ingen vesentlig fysisk eksponering.",
        "Egen intern plattform og sterk ingeniørkultur bygget over et tiår.",
        "Én av få banker som tallfester AI-verdi offentlig – i hundremillioner SGD årlig.",
        "God lønnsomhet, men mindre absolutt størrelse enn globale storbanker."],
    th: "Best dokumenterte AI-avkastning blant banker – en modell for omstilling.",
    rk: "Lite hjemmemarked; ledelsesskifte kan endre tempo." },
  { n: "Bank of America", t: "BAC", x: "NYSE · USA", i: "bank", s: [8,9,8,1,8,8,9],
    r: ["Langsiktig teknologisatsing med tydelig fokus på AI i kundeflaten.",
        "En av USAs største forbrukerbaser gir dype transaksjons- og atferdsdata.",
        "Assistenten Erica har gjennomført milliarder interaksjoner; utvidet til ansatte og bedriftskunder.",
        "Ingen vesentlig fysisk eksponering.",
        "Stort teknologibudsjett og en av bankene med flest AI-patenter.",
        "Målbar reduksjon i kundesentervolum og høy digital adopsjon.",
        "Svært sterk finansiell kapasitet."],
    th: "Pioner på AI-assistent i masseskala.",
    rk: "Mer inkrementell enn radikal AI-strategi." },
  { n: "Royal Bank of Canada", t: "RY", x: "NYSE/TSX · Canada", i: "bank", s: [8,8,7,1,9,7,8],
    r: ["Har kommunisert konkrete mål for verdiskaping fra AI; AI er del av konsernstrategien.",
        "Dominerende posisjon i Canada gir brede kunde- og markedsdata.",
        "AI i rådgivning og kapitalmarked (bl.a. AI-basert handelsplattform).",
        "Ingen vesentlig fysisk eksponering.",
        "Borealis AI er et av de sterkeste bankeide forskningsmiljøene i verden.",
        "Verdimål kommunisert; foreløpig delvis dokumentert.",
        "Sterk balanse i et oligopolmarked."],
    th: "Forskningsdrevet AI-bank med tydelige verdimål.",
    rk: "Begrenset skala utenfor Nord-Amerika." },
  { n: "Morgan Stanley", t: "MS", x: "NYSE · USA", i: "bank", s: [8,8,8,1,8,7,8],
    r: ["Tidlig strategisk partnerskap med OpenAI for formuesrådgiverne.",
        "Dyp research- og formuesforvaltningsdata.",
        "AI-assistent og møtereferat-verktøy brukt av nesten alle rådgivere.",
        "Ingen vesentlig fysisk eksponering.",
        "Sterk partnertilgang, mindre egen modellutvikling.",
        "Dokumenterte tidsbesparelser for rådgivere; inntektseffekt mindre klar.",
        "Stabil inntjening fra formuesforvaltning."],
    th: "Ledende på generativ AI i formuesforvaltning.",
    rk: "Avhengig av eksterne modelleverandører." },
  { n: "BBVA", t: "BBVA", x: "BME · Spania", i: "bank", s: [8,7,7,1,7,6,7],
    r: ["Stor avtale om ChatGPT Enterprise til ansatte; AI satt i kjernen av strategien.",
        "Gode data i Spania og Mexico, men fragmentert over markeder.",
        "Rask utrulling av GenAI-assistenter og agenter for ansatte og kunder.",
        "Ingen vesentlig fysisk eksponering.",
        "Sterk digital kultur, men mindre forskningskapasitet enn amerikanske storbanker.",
        "Tidlige produktivitetstall, få finansielle tall.",
        "Moderat; eksponert mot fremvoksende markeder og valuta."],
    th: "Europas mest offensive AI-adoptør blant storbankene.",
    rk: "Valuta- og fremvoksende-markeder-risiko." },

  /* ---------------- FORSIKRING ---------------- */
  { n: "Ping An Insurance", t: "2318", x: "HKEX · Kina", i: "ins", s: [9,10,9,3,9,8,7],
    r: ["Har i over et tiår posisjonert seg som teknologikonsern med forsikring i kjernen.",
        "Hundrevis av millioner kunder på tvers av forsikring, bank og helse – enestående databredde.",
        "AI-kundeservice håndterer det store flertallet av henvendelser; AI i skadeoppgjør og helse.",
        "Noe IoT og bildeanalyse for skade; lite robotikk.",
        "Tusenvis av forskere og en av verdens største patentporteføljer innen fintech/AI.",
        "Rapporterer betydelige kostnadsbesparelser fra AI-drevet service og salg.",
        "Stor balanse, men eksponering mot kinesisk eiendom og makro."],
    th: "Verdens mest AI-integrerte forsikringskonsern.",
    rk: "Kina-risiko, eiendomseksponering og geopolitikk." },
  { n: "Progressive", t: "PGR", x: "NYSE · USA", i: "ins", s: [8,10,7,3,8,9,8],
    r: ["Datadrevet prising er selve forretningsmodellen.",
        "Telematikkprogrammet Snapshot har samlet enorme mengder kjøredata – en unik risikodatabase.",
        "AI i skadebehandling, bildebasert takst og kundeservice.",
        "Telematikk og sensordata fra biler; ikke robotikk.",
        "Sterk intern analytics-kultur gjennom tiår.",
        "Bransjeledende combined ratio og markedsandelsvekst drevet av bedre prising.",
        "Sterk kapital og høy lønnsomhet."],
    th: "Forsikringens opprinnelige «dataselskap» – AI forsterker prisingsfortrinnet.",
    rk: "Selvkjørende biler kan endre bilforsikringsmarkedet fundamentalt." },
  { n: "Allianz", t: "ALV", x: "XETRA · Tyskland", i: "ins", s: [8,8,8,2,7,7,9],
    r: ["AI uttalt som sentral i konsernstrategien med globale programmer.",
        "Global skala i skade, liv og kapitalforvaltning (inkl. PIMCO).",
        "Agentisk skadebehandling – multi-agentsystem som behandler enkle krav – i produksjon i flere markeder.",
        "Begrenset fysisk eksponering.",
        "Partnerskap med ledende AI-labber og voksende intern kapasitet.",
        "Effektiviseringsmål kommunisert, delvis dokumentert.",
        "Svært sterk solvens og kapital."],
    th: "Europas ledende forsikrer på agentisk skadebehandling.",
    rk: "Kompleks struktur gir tregere utrulling på tvers av land." },
  { n: "Chubb", t: "CB", x: "NYSE · Sveits/USA", i: "ins", s: [8,8,7,2,7,7,9],
    r: ["Uttalt mål om å digitalisere og automatisere store deler av underwriting og drift.",
        "Bred global skadeforsikringsdata på tvers av segmenter.",
        "Automatisering av underwriting og skadebehandling med mål om vesentlig lavere bemanning i drift.",
        "Begrenset fysisk eksponering.",
        "Moderat intern kapasitet, partnerbasert.",
        "Kommuniserte effektivitetsgevinster; sterke marginer.",
        "Svært sterk kapital og disiplinert balanse."],
    th: "Disiplinert underwriter som bruker AI til strukturelle kostnadskutt.",
    rk: "Gjennomføringsrisiko ved omstilling av arbeidsstyrken." },
  { n: "AXA", t: "CS", x: "Euronext · Frankrike", i: "ins", s: [8,8,7,2,7,6,8],
    r: ["Tidlig GenAI-satsing med intern plattform for alle ansatte.",
        "Global data innen skade, helse og liv.",
        "Intern sikker GPT-plattform for ansatte; AI i skadebehandling og underwriting.",
        "Begrenset fysisk eksponering.",
        "Solid, i stor grad partnerbasert.",
        "Produktivitetsdata begrenset offentlig.",
        "Sterk kapitalposisjon."],
    th: "Bred GenAI-adopsjon med god styring og risikokontroll.",
    rk: "Lite differensiering mot konkurrentene." },
  { n: "Zurich Insurance", t: "ZURN", x: "SIX · Sveits", i: "ins", s: [7,8,7,2,7,6,8],
    r: ["AI er del av strategien med et sentralt AI-program, men mindre profilert enn de fremste.",
        "Global kommersiell skadedata fra store bedriftskunder gir rik risikoinnsikt.",
        "GenAI i underwriting og skade – bl.a. analyse av dokumenter, krav og risikorapporter.",
        "Begrenset fysisk eksponering; noe risikoingeniørarbeid med sensordata.",
        "Solid intern kapasitet og partnerskap med store skyleverandører.",
        "Tidlige effekter i underwriting-produktivitet, få finansielle tall.",
        "Sterk kapital og solvens."],
    th: "Solid adoptør innen kommersiell forsikring.",
    rk: "Moderat tempo." },
  { n: "Gjensidige", t: "GJF", x: "Oslo Børs · Norge", i: "ins", s: [7,7,6,1,6,6,7],
    r: ["Blant Nordens mest digitale skadeforsikrere; AI brukt i prising og skade.",
        "Sterk posisjon i Norge gir gode data, men lite marked.",
        "Automatisert behandling av enkle skadesaker og digital kundedialog.",
        "Ingen vesentlig fysisk eksponering.",
        "Begrenset skala på AI-talent.",
        "Lav kostnadsratio sammenlignet med bransjen.",
        "God lønnsomhet, men mindre absolutt størrelse."],
    th: "Nordisk referanse – effektiv, men skalabegrenset.",
    rk: "Små markeder begrenser data og investeringsevne." },

  /* ---------------- HELSE & FARMA ---------------- */
  { n: "Eli Lilly", t: "LLY", x: "NYSE · USA", i: "health", s: [9,8,7,6,8,6,10],
    r: ["Ledelsen har gjort AI til del av FoU-strategien; bygger bransjens største AI-superdatamaskin sammen med NVIDIA.",
        "Store kliniske og molekylære datasett; tilbyr egne modeller (TuneLab) til biotek i bytte mot data.",
        "AI i oppdagelse, klinisk utvikling og kommersiell drift; agentiske verktøy under utrulling.",
        "Automatiserte laboratorier og massiv utbygging av høyautomatiserte fabrikker.",
        "Sterk intern AI-organisasjon og tunge partnerskap.",
        "FoU-effekten tar år å bevise – fortsatt tidlig.",
        "Verdens mest verdifulle farmaselskap; GLP-1-inntjening finansierer satsingen."],
    th: "Har kapitalen og viljen til å bli farmas «AI-fabrikk».",
    rk: "Bevis for AI-akselerert FoU kommer først om flere år." },
  { n: "Roche", t: "ROG", x: "SIX · Sveits", i: "health", s: [9,9,7,7,9,6,8],
    r: ["«Lab-in-the-loop» i Genentech er kjernen i FoU – modeller og lab forbedrer hverandre.",
        "Unik kombinasjon av diagnostikkdata (Roche Diagnostics) og farma-/real-world-data.",
        "AI-agenter i forskning, regulatorisk dokumentasjon og drift.",
        "Labautomasjon og diagnostikkinstrumenter i global skala.",
        "Sterke forskningsmiljøer i Genentech med egen AI-gruppe og NVIDIA-partnerskap.",
        "Tidlig, men konkrete AI-designede kandidater i utvikling.",
        "Sterk kontantstrøm."],
    th: "Best posisjonert til å koble diagnostikkdata og AI-drevet legemiddelutvikling.",
    rk: "Patentutløp og prispress." },
  { n: "Intuitive Surgical", t: "ISRG", x: "Nasdaq · USA", i: "health", s: [8,9,5,9,8,7,8],
    r: ["Robotkirurgi og data fra inngrep er hele strategien.",
        "Data fra millioner av robotassisterte inngrep – en vanskelig kopierbar vollgrav.",
        "Digitale verktøy for kirurger (analyse, simulering), mindre agentisk.",
        "Markedsleder på kirurgiske roboter; neste steg er AI-assistert og delvis autonom kirurgi.",
        "Sterk ingeniørbase innen robotikk og bildeanalyse.",
        "Høye marginer og tilbakevendende inntekter fra installert base.",
        "Netto kontantposisjon og god lønnsomhet."],
    th: "Helsevesenets fremste fysiske AI-plattform.",
    rk: "Konkurranse fra nye robotplattformer; prispress fra sykehus." },
  { n: "UnitedHealth Group", t: "UNH", x: "NYSE · USA", i: "health", s: [8,10,8,2,8,6,6],
    r: ["Optum posisjonerer AI som sentral i administrasjon og omsorg.",
        "Uovertruffen helse- og kravdata gjennom forsikring, Optum og leverandørnettverk.",
        "Hundrevis av AI-use cases i produksjon i kravbehandling, koding og kundeservice.",
        "Lite fysisk eksponering.",
        "Stor intern teknologiorganisasjon i Optum.",
        "Effektivitet synlig, men overskygget av kostnadssjokk og omdømmeproblemer.",
        "Presset av marginfall, regulatorisk granskning og ledelsesskifte."],
    th: "Har dataene – men må gjenvinne tillit og marginer.",
    rk: "Regulering og kontrovers rundt AI i kravbehandling." },
  { n: "AstraZeneca", t: "AZN", x: "LSE/Nasdaq · UK", i: "health", s: [8,8,7,5,8,6,8],
    r: ["AI integrert i hele FoU-kjeden; tydelige mål for datadrevet utvikling.",
        "Store genomikk- og kliniske data.",
        "AI i målidentifikasjon, klinisk design og dokumentasjon.",
        "Labautomasjon og digitalisert produksjon.",
        "Sterke interne datavitenskapsmiljøer og partnerskap.",
        "Tidlig, men økende andel AI-støttede kandidater.",
        "Sterk vekst og kontantstrøm."],
    th: "Bred og moden AI-integrasjon i FoU.",
    rk: "Lang tidshorisont for bevist effekt." },
  { n: "Sanofi", t: "SAN", x: "Euronext · Frankrike", i: "health", s: [8,7,7,4,7,6,7],
    r: ["Uttalt «all in» på AI i hele verdikjeden.",
        "Gode data, men mindre unike enn diagnostikk- eller forsikringsaktører.",
        "Intern AI-app for beslutningsstøtte; partnerskap med OpenAI og Formation Bio.",
        "Digitaliserte fabrikker (evolutive facilities).",
        "Partnerdrevet stakk.",
        "Raskere rekruttering til studier rapportert.",
        "Solid, men moderat vekst."],
    th: "Offensiv AI-adoptør blant europeisk farma.",
    rk: "Pipeline-avhengig." },
  { n: "Johnson & Johnson", t: "JNJ", x: "NYSE · USA", i: "health", s: [7,8,6,7,7,5,9],
    r: ["AI prioritert i både farma og MedTech, men mindre profilert.",
        "Bred klinisk og kirurgisk data.",
        "GenAI i FoU og kommersiell drift; mange use cases er nedprioritert til færre med høy verdi.",
        "Kirurgiske robotplattformer under utvikling og partnerskap med NVIDIA for fysisk AI i kirurgi.",
        "Solid intern kapasitet.",
        "Begrenset dokumentasjon.",
        "Svært sterk balanse (AAA-kreditt)."],
    th: "Finansielt sterk med opsjon på fysisk AI i kirurgi.",
    rk: "Etterslep mot Intuitive i robotkirurgi; rettssaker." },
  { n: "Novo Nordisk", t: "NOVO B", x: "Nasdaq CPH · Danmark", i: "health", s: [7,8,6,5,7,5,7],
    r: ["AI satt høyt på agendaen, men selskapet er i en omstillingsfase.",
        "Store kliniske data innen diabetes og fedme.",
        "AI-agenter i klinisk dokumentasjon og regulatorisk skriving.",
        "Høyautomatisert produksjonsoppbygging.",
        "Tilgang til supercomputeren Gefion via eierstiftelsen.",
        "Lite dokumentert finansiell effekt.",
        "Presset av konkurranse, prisfall og restrukturering."],
    th: "Gode forutsetninger, men fokus er på å forsvare kjernevirksomheten.",
    rk: "Konkurranse i GLP-1-markedet." },

  /* ---------------- ENERGI & KRAFT ---------------- */
  { n: "Saudi Aramco", t: "2222", x: "Tadawul · Saudi-Arabia", i: "energy", s: [8,9,6,6,6,6,10],
    r: ["AI er del av nasjonal og konsernstrategi; tett koblet til Saudi-Arabias AI-satsing.",
        "Verdens største reservoar- og produksjonsdata.",
        "Egen industriell språkmodell (Metabrain) og AI-støtte i drift.",
        "Digitale tvillinger, droner og fjernstyring i felt.",
        "Bygger kapasitet, men avhenger av partnere.",
        "Effektivitetstall rapporteres, men lite verifiserbare.",
        "Enorm kontantstrøm."],
    th: "Ubegrenset kapital og data – spørsmålet er gjennomføring.",
    rk: "Statlig eierskap og oljeprisavhengighet." },
  { n: "Equinor", t: "EQNR", x: "Oslo Børs · Norge", i: "energy", s: [7,8,7,8,7,7,8],
    r: ["Digitalisering og AI er tydelig del av strategien, særlig i drift.",
        "Svært godt instrumenterte felt (f.eks. Johan Sverdrup) gir rik sanntidsdata.",
        "AI i boreplanlegging, vedlikehold og dokumentanalyse.",
        "Fjernstyrte og ubemannede installasjoner, robotinspeksjon og droner på sokkelen.",
        "Solid intern data-/AI-organisasjon og partnerskap.",
        "Rapporterer konkrete besparelser fra AI i drift og vedlikehold.",
        "Sterk balanse."],
    th: "Blant verdens mest digitaliserte produsenter – ledende på fysisk AI offshore.",
    rk: "Politisk og regulatorisk risiko; energiomstilling." },
  { n: "Shell", t: "SHEL", x: "LSE · UK", i: "energy", s: [7,8,7,6,7,7,8],
    r: ["AI integrert i drift og handel.",
        "Global produksjons- og handelsdata.",
        "AI-plattform for prediktivt vedlikehold på tusenvis av utstyrsenheter.",
        "Digitale tvillinger og robotinspeksjon.",
        "Partnerskap med AI-programvareleverandører; solid intern stab.",
        "Dokumenterte reduksjoner i nedetid.",
        "Sterk kontantstrøm."],
    th: "Bred, moden AI-bruk i drift og trading.",
    rk: "Strategisk usikkerhet rundt energiomstilling." },
  { n: "ExxonMobil", t: "XOM", x: "NYSE · USA", i: "energy", s: [6,8,6,7,6,7,10],
    r: ["Pragmatisk tilnærming – AI som effektiviseringsverktøy, mindre strategisk profil.",
        "Store reservoar- og produksjonsdata.",
        "Moderat utrulling av digitale agenter.",
        "Autonom/automatisert boring og drift i bl.a. Guyana og Permian.",
        "Solid ingeniørkapasitet.",
        "Kostnadsprogrammer med teknologi-komponent gir målbare besparelser.",
        "Svært sterk balanse."],
    th: "Stille operatør som bruker AI og automasjon til lavere kostnad per fat.",
    rk: "Lav strategisk ambisjon på AI." },
  { n: "NextEra Energy", t: "NEE", x: "NYSE · USA", i: "energy", s: [7,8,6,6,7,7,8],
    r: ["AI både i drift og som vekstdriver gjennom kraft til datasentre.",
        "Stor flåte av vind, sol og nett med sensordata.",
        "AI i prognoser, handel og kundeservice.",
        "Droner og robotinspeksjon av anlegg.",
        "Solid intern data- og analysekapasitet.",
        "Lave driftskostnader per MWh sammenlignet med bransjen.",
        "Sterk, men kapitalkrevende."],
    th: "Vinner både som AI-bruker og som kraftleverandør til AI.",
    rk: "Rentenivå og regulering." },
  { n: "TotalEnergies", t: "TTE", x: "Euronext · Frankrike", i: "energy", s: [7,7,6,6,7,6,9],
    r: ["AI-program med partnerskap med europeiske AI-aktører (bl.a. Mistral) og egne digitale fabrikker.",
        "Gode drifts- og handelsdata, men mindre samlet enn hos de største.",
        "GenAI-verktøy for ansatte; agenter i tidlig fase i drift og handel.",
        "Robotikk og droner i inspeksjon; digitale tvillinger på anlegg.",
        "Partnerbasert stakk med intern «Digital Factory».",
        "Få offentlige tall på AI-effekt.",
        "Sterk balanse og integrert modell inkl. kraft."],
    th: "Europeisk energiaktør med offensiv AI-partnerstrategi.",
    rk: "Gjennomføring og strategisk spredning." },
  { n: "BP", t: "BP", x: "LSE · UK", i: "energy", s: [6,7,6,6,6,6,5],
    r: ["AI-satsing finnes (bl.a. med Palantir), men strategien har vært ustabil.",
        "Gode produksjonsdata fra digitale tvillinger av anlegg.",
        "Digitale tvillinger og AI-verktøy i drift og handel.",
        "Robotikk og droner i inspeksjon.",
        "Partnerbasert stakk.",
        "Noe dokumentert effekt i oppetid og drift.",
        "Presset balanse, aktivistpress og strategisk omlegging."],
    th: "Har verktøyene, men mangler ro og kapital.",
    rk: "Strategi- og ledelsesrisiko." },

  /* ---------------- BIL & MOBILITET ---------------- */
  { n: "Tesla", t: "TSLA", x: "Nasdaq · USA", i: "auto", s: [10,10,6,10,10,6,9],
    r: ["Hele selskapet posisjoneres som AI- og robotikkselskap – bil er bærer av teknologien.",
        "Videodata fra millioner av biler i drift – trolig verdens største datasett for kjøring i virkeligheten.",
        "Mindre fokus på digitale agenter i administrasjon; integrasjon med xAI/Grok.",
        "Ende-til-ende selvkjøring, robotaxi-tjeneste og humanoidroboten Optimus.",
        "Egne AI-chips, store treningsklynger og topp AI-talent.",
        "Robotaxi og Optimus er fortsatt små inntektskilder; bilmarginene er presset.",
        "Sterk kontantbeholdning, men volatil kjernevirksomhet."],
    th: "Den rene satsingen på fysisk AI blant bilprodusentene.",
    rk: "Høye forventninger, regulering av selvkjøring og nøkkelpersonrisiko." },
  { n: "XPeng", t: "XPEV", x: "NYSE/HKEX · Kina", i: "auto", s: [9,7,6,8,8,4,5],
    r: ["Kaller seg «AI-bilselskap»; satser på selvkjøring, robotaxi, humanoider og flygende biler.",
        "Voksende flåtedata, men mindre enn de største.",
        "AI-assistenter i bilen, mindre i drift.",
        "Egen selvkjøringsstakk og humanoidrobot under utvikling.",
        "Egenutviklede AI-chips og sterk programvarestab.",
        "Lite lønnsomhet så langt.",
        "Begrenset kapital, avhengig av partnere (bl.a. Volkswagen)."],
    th: "Kinas mest AI-offensive bilprodusent – høy opsjonsverdi.",
    rk: "Lønnsomhet og priskrig i Kina." },
  { n: "BYD", t: "1211", x: "HKEX · Kina", i: "auto", s: [7,8,5,8,6,6,8],
    r: ["Førerassistent satt som standard i hele modellspekteret – AI brukes som volumvåpen.",
        "Største elbilflåte gir enorme kjøredata.",
        "Moderat utrulling av digitale agenter.",
        "Høyt automatisert, vertikalt integrert produksjon og bred ADAS.",
        "Stor ingeniørbase, men mindre AI-forskning i verdensklasse.",
        "Skala gir kostnadsfortrinn; AI-effekt vanskelig å isolere.",
        "Sterk, men priskrig presser marginer."],
    th: "Skala og produksjonsautomasjon gjør BYD til en undervurdert fysisk AI-aktør.",
    rk: "Priskrig, tariffer og geopolitikk." },
  { n: "Mercedes-Benz", t: "MBG", x: "XETRA · Tyskland", i: "auto", s: [7,7,6,7,6,5,7],
    r: ["AI i bil og fabrikk med klar ambisjon.",
        "Premiumflåte med rike data, men mindre volum.",
        "AI-assistenter i bil og intern GenAI.",
        "Godkjent nivå 3-selvkjøring og investering i humanoidroboter for fabrikk.",
        "Partnerbasert (bl.a. NVIDIA).",
        "Begrenset dokumentert effekt.",
        "Presset av Kina-salg og tariffer."],
    th: "Europas mest avanserte tradisjonelle bilprodusent på autonomi.",
    rk: "Svak Kina-utvikling." },
  { n: "Toyota", t: "7203", x: "TSE · Japan", i: "auto", s: [6,7,5,7,6,5,9],
    r: ["Forsiktig, partnerbasert AI-strategi.",
        "Verdens største bilflåte, men mindre utnyttet data.",
        "Lav profil på digitale agenter.",
        "Woven City som testarena, partnerskap om robotaxi og lang tradisjon for produksjonsautomasjon.",
        "Moderat intern kapasitet; Toyota Research Institute innen robotikk.",
        "Effekt vanskelig å isolere.",
        "Svært sterk balanse."],
    th: "Kapitalsterk «fast follower» med robotikkforskning.",
    rk: "Kan bli forbigått av programvaredefinerte konkurrenter." },
  { n: "General Motors", t: "GM", x: "NYSE · USA", i: "auto", s: [6,8,5,6,6,4,7],
    r: ["Avviklet robotaxi-satsingen Cruise; fokus flyttet til førerassistanse.",
        "Super Cruise har samlet store mengder motorveidata.",
        "Moderat GenAI i drift.",
        "Avansert førerassistanse; robotaxi-ambisjon nedskalert.",
        "Rekrutterer AI-talent, partnerskap med NVIDIA.",
        "Lite effekt synlig.",
        "God kontantstrøm, men syklisk."],
    th: "Sterke data, svekket ambisjon.",
    rk: "Strategisk retrett fra autonomi." },
  { n: "Volkswagen", t: "VOW3", x: "XETRA · Tyskland", i: "auto", s: [6,7,5,6,5,4,6],
    r: ["Programvare har vært et smertepunkt; nå partnerbasert omstilling.",
        "Stor flåte, men fragmentert dataarkitektur.",
        "Interne GenAI-verktøy.",
        "Robotikk i fabrikk; autonomi via partnere.",
        "Satser på partnere (Rivian, XPeng) for programvare.",
        "Lite dokumentert effekt.",
        "Presset av kostnader og Kina."],
    th: "Kjøper seg tilbake i programvarekappløpet.",
    rk: "Gjennomføring og fagforeninger." },

  /* ---------------- INDUSTRI & MASKINER ---------------- */
  { n: "Siemens", t: "SIE", x: "XETRA · Tyskland", i: "ind", s: [9,9,8,8,9,7,9],
    r: ["Posisjonerer seg som teknologiselskap for industriell AI; omfattende oppkjøp innen simuleringsprogramvare.",
        "Installert base av automasjon og programvare i fabrikker verden over.",
        "Industrial Copilot og agenter for ingeniørarbeid og automasjonsprogrammering.",
        "Digitale tvillinger og automasjon som operativsystem for fysisk AI.",
        "Sterk programvareorganisasjon og partnerskap med NVIDIA og Microsoft.",
        "Programvaredelen vokser med gode marginer.",
        "Sterk balanse."],
    th: "Operativsystemet for den AI-drevne fabrikken.",
    rk: "Konjunkturfølsom fabrikkautomasjon." },
  { n: "Deere & Company", t: "DE", x: "NYSE · USA", i: "ind", s: [8,9,5,9,8,7,8],
    r: ["Visjon om fullt autonomt landbruk innen få år.",
        "Data fra hundretusener av tilkoblede maskiner og millioner av dekar.",
        "Begrenset bruk av digitale agenter i administrasjon.",
        "See & Spray (kamerabasert sprøyting) og autonome traktorer i drift.",
        "Sterk intern AI- og robotikkstab (bl.a. via Blue River).",
        "Abonnementer og presisjonsprodukter gir dokumenterte kundebesparelser.",
        "Solid, men syklisk."],
    th: "Verdens ledende fysiske AI-aktør i landbruk.",
    rk: "Landbrukssyklus og handelspolitikk." },
  { n: "Caterpillar", t: "CAT", x: "NYSE · USA", i: "ind", s: [7,8,5,9,7,7,9],
    r: ["Autonomi og digitale tjenester er tydelig strategisk satsing.",
        "Over en million tilkoblede maskiner.",
        "AI-assistenter for forhandlere og service.",
        "Ledende på autonom gruvetransport over mange år.",
        "Solid intern kapasitet og NVIDIA-partnerskap.",
        "Tjenesteinntekter vokser.",
        "Sterk balanse."],
    th: "Bevist fysisk AI i gruve og anlegg.",
    rk: "Syklisk råvareeksponering." },
  { n: "Schneider Electric", t: "SU", x: "Euronext · Frankrike", i: "ind", s: [8,8,7,8,7,7,8],
    r: ["AI både som produkt og som etterspørselsdriver (datasentre).",
        "Stor installert base av energistyring og automasjon.",
        "AI-agenter i energistyring og intern drift.",
        "Industriell automasjon og digitale tvillinger.",
        "Partnerskap med NVIDIA om datasenterdesign.",
        "Sterk vekst fra datasentersegmentet.",
        "Sterk balanse."],
    th: "Dobbel vinner: leverer til AI-infrastruktur og bruker AI i drift.",
    rk: "Avhengig av datasenter-capex." },
  { n: "Kongsberg Gruppen", t: "KOG", x: "Oslo Børs · Norge", i: "ind", s: [7,7,5,8,7,6,7],
    r: ["Autonomi er kjernekompetanse i maritim og forsvar.",
        "Gode maritime driftsdata, men mindre skala.",
        "Digitale tvillinger og programvare via Kongsberg Digital.",
        "Autonome fartøy og undervannsdroner.",
        "Sterk ingeniørbase.",
        "Sterk vekst, særlig i forsvar.",
        "Solid."],
    th: "Nordens fremste autonomi-selskap.",
    rk: "Avhengig av forsvarsbudsjetter." },
  { n: "ABB", t: "ABBN", x: "SIX · Sveits", i: "ind", s: [7,7,6,7,7,6,8],
    r: ["AI i elektrifisering og automasjon, men har valgt å selge robotikkdivisjonen.",
        "Stor installert base.",
        "AI-verktøy for service og drift.",
        "Automasjon i prosessindustri; robotikk ut av konsernet.",
        "Solid programvarekapasitet.",
        "Gode marginer i elektrifisering.",
        "Sterk balanse."],
    th: "Solid AI-bruker – men har gitt fra seg robotikk-opsjonen.",
    rk: "Mister eksponering mot humanoider/robotikk." },
  { n: "Honeywell", t: "HON", x: "Nasdaq · USA", i: "ind", s: [7,8,7,7,7,6,7],
    r: ["AI i automasjon, men selskapet deles opp.",
        "Bred industriell installert base.",
        "AI-agenter i industriprogramvare.",
        "Automasjon i lager, fly og prosess.",
        "Solid programvarekapasitet.",
        "Moderat dokumentert effekt.",
        "Oppsplitting tar ledelsesfokus."],
    th: "Gode byggesteiner, men omstilling gjennom oppdeling.",
    rk: "Gjennomføringsrisiko ved oppdeling." },
  { n: "Fanuc", t: "6954", x: "TSE · Japan", i: "ind", s: [6,7,4,9,6,6,8],
    r: ["Robotprodusent med økende AI-fokus, men tradisjonelt maskinvaredrevet.",
        "Stor installert robotbase gir driftsdata, men lite utnyttet til AI-tjenester.",
        "Lite bruk av digitale agenter.",
        "Verdens ledende industrirobotprodusent; partnerskap med NVIDIA om AI-styrte roboter.",
        "Moderat programvare-/AI-kapasitet sammenlignet med maskinvaretyngden.",
        "Høye marginer historisk, men lite AI-spesifikk effekt.",
        "Sterk balanse med netto kontanter."],
    th: "Hardware-leder – må bevise AI-programvare.",
    rk: "Kinesiske konkurrenter." },

  /* ---------------- VAREHANDEL & E-HANDEL ---------------- */
  { n: "Amazon", t: "AMZN", x: "Nasdaq · USA", i: "retail", s: [10,10,9,10,10,9,10],
    r: ["AI er sentralt i alle forretningsområder; ledelsen har varslet at agenter vil endre arbeidsstyrken.",
        "Kjøps-, søk- og logistikkdata fra hundrevis av millioner kunder.",
        "Shoppingassistent, agenter for selgere og interne agenter i stor skala.",
        "Over én million roboter i lagrene; leveringsdroner og robotaxi via Zoox.",
        "Egne AI-chips, AWS og dype partnerskap med frontier-labber.",
        "Klare kostnadsreduksjoner i logistikk og vekst i AI-drevet annonsering.",
        "Ekstrem kapasitet."],
    th: "Den sterkeste kombinasjonen av digitale og fysiske agenter i noe børsnotert selskap.",
    rk: "Regulering og enorm capex." },
  { n: "Walmart", t: "WMT", x: "NYSE · USA", i: "retail", s: [9,9,8,7,8,8,9],
    r: ["Toppledelsen har sagt at AI vil endre alle jobber; omfattende omstilling.",
        "Data fra butikker, netthandel og annonsenettverk i enorm skala.",
        "Shoppingagent for kunder, agenter for ansatte og selgere, og agentisk handel via ChatGPT.",
        "Automatiserte distribusjonssentre i samarbeid med robotleverandører.",
        "Bygger intern kapasitet og partnerskap.",
        "Marginforbedring og vekst i annonser og e-handel.",
        "Sterk balanse."],
    th: "Den tradisjonelle forhandleren som omstiller seg raskest.",
    rk: "Lavmargin-modell gir lite feilmargin." },
  { n: "Alibaba", t: "BABA", x: "NYSE/HKEX · Kina", i: "retail", s: [9,9,8,6,9,6,8],
    r: ["Har gjort AI til konsernets hovedprioritet med store investeringer.",
        "Kinas største handelsdata.",
        "AI-agenter i handel og for selgere; egne Qwen-modeller.",
        "Logistikkautomasjon via Cainiao.",
        "Egne modeller i verdensklasse og stor sky.",
        "Skyinntekter fra AI vokser; handelseffekt mindre klar.",
        "Sterk, men under geopolitisk press."],
    th: "Kinas AI-leder innen handel med egne grunnmodeller.",
    rk: "Regulering og geopolitikk." },
  { n: "JD.com", t: "JD", x: "Nasdaq/HKEX · Kina", i: "retail", s: [8,9,7,8,7,6,6],
    r: ["AI og automasjon kjernen i logistikkmodellen.",
        "Egen logistikk gir unike data.",
        "AI-agenter for kundeservice og selgere.",
        "Høyautomatiserte lagre, leveringsroboter og droner.",
        "Solid intern kapasitet.",
        "Lavere kostnad per pakke.",
        "Presset av priskrig."],
    th: "Fysisk AI-leder i kinesisk handel.",
    rk: "Konkurranse og marginer." },
  { n: "Ocado Group", t: "OCDO", x: "LSE · UK", i: "retail", s: [8,7,5,9,8,4,3],
    r: ["Hele selskapet er en AI- og robotikkplattform for dagligvare.",
        "Data fra robotlagre og partnere.",
        "Begrenset digital agentbruk.",
        "Avanserte robotlagre og egenutviklede robotarmer.",
        "Sterk robotikkingeniørbase.",
        "Ennå ikke lønnsomt.",
        "Svak balanse."],
    th: "Teknologisk leder, finansielt sårbar.",
    rk: "Kontantforbruk og avhengighet av få partnere." },
  { n: "Target", t: "TGT", x: "NYSE · USA", i: "retail", s: [6,7,6,4,5,4,6],
    r: ["AI-verktøy for ansatte og kunder, men mindre strategisk dybde enn Walmart og Amazon.",
        "Gode kunde- og lojalitetsdata (Target Circle).",
        "GenAI-assistent for butikkansatte og AI i sortiment/prognoser.",
        "Moderat lagerautomasjon i distribusjonssentre.",
        "Moderat intern kapasitet.",
        "Svak – vekst og marginer er under press.",
        "Presset av svak vekst og ledelsesskifte."],
    th: "Følger, ikke leder.",
    rk: "Markedsandelstap." },
  { n: "Costco", t: "COST", x: "Nasdaq · USA", i: "retail", s: [4,7,3,3,4,4,9],
    r: ["Bevisst konservativ teknologistrategi; fokus på enkelhet og lave priser.",
        "Medlemsdata fra over 100 mill. kortholdere, men lite utnyttet til AI.",
        "Begrenset bruk av digitale agenter.",
        "Lite automasjon i butikk og lager.",
        "Svak intern AI-kapasitet.",
        "Ingen dokumentert AI-effekt.",
        "Svært sterk balanse og lojalitet."],
    th: "Fantastisk forretningsmodell, men AI-etternøler.",
    rk: "Kan bli utfordret av agentisk handel." },


  /* ---------------- TRANSPORT & LOGISTIKK ---------------- */
  { n: "DHL Group", t: "DHL", x: "XETRA · Tyskland", i: "logistics", s: [7,8,6,8,6,6,7],
    r: ["Robotikk og AI er eksplisitt prioritert i konsernstrategien, med «accelerated digitalization» som ett av hovedsporene.",
        "Global pakke-, ekspress- og kontraktslogistikkdata på tvers av over 200 land gir bred innsikt i vareflyt.",
        "AI i kundeservice, tolldeklarasjoner og prognoser; agenter mest i støttefunksjoner så langt.",
        "En av verdens største utrullinger av lagerroboter – mobile plukkroboter og roboter for lossing av containere i stor skala.",
        "I hovedsak partnerbasert med robot- og AI-leverandører, mindre egen grunnteknologi.",
        "Rapporterer produktivitetsgevinster per lager, men lite samlet finansiell kvantifisering.",
        "Solid balanse og kontantstrøm, men utsatt for handelskonflikter og tollregimer."],
    th: "Ledende fysisk AI i kontraktslogistikk – fra pilot til tusenvis av roboter.",
    rk: "Global handelsusikkerhet og svak pakkevekst i Tyskland." },
  { n: "UPS", t: "UPS", x: "NYSE · USA", i: "logistics", s: [7,8,6,7,6,6,6],
    r: ["Ledelsen har lansert «network of the future» med automasjon og konsolidering av anlegg i sentrum.",
        "Ruteoptimaliseringssystemet ORION har samlet ruteoptimaliseringsdata i over et tiår; enorm pakkedata.",
        "AI i kundeservice, prising og kontraktsforhandling; agentisk bruk er tidlig.",
        "Høy andel av pakkevolumet går gjennom automatiserte sorteringsanlegg; testing av roboter for lossing.",
        "Moderat intern AI-kapasitet, supplert av partnere.",
        "Kostnadsprogrammer i milliardklassen der automasjon er en vesentlig del.",
        "Presset av bevisst volumreduksjon fra største kunde og svakere marginer."],
    th: "Automatiserer for å forsvare marginer i et krympende volum.",
    rk: "Volumnedgang og fagforeningsavtaler som begrenser automasjonstempo." },
  { n: "FedEx", t: "FDX", x: "NYSE · USA", i: "logistics", s: [7,8,6,6,6,6,7],
    r: ["Data og AI er en uttalt del av omstillingsprogrammet (bl.a. FedEx Dataworks).",
        "Milliarder av pakkehendelser gir unike data om forsyningskjeder.",
        "AI i kundeservice, prognoser og tollbehandling.",
        "Robotikk i sortering og lasting av trailere i utvalgte anlegg.",
        "Moderat intern kapasitet; partnerskap for robotikk.",
        "Kostnadsprogrammer med dokumenterte besparelser, AI-andelen er uklar.",
        "Solid, men syklisk og under strukturell omlegging (utskillelse av Freight)."],
    th: "Datadrevet omstilling av nettverket med opsjon på å selge datainnsikt.",
    rk: "Syklisk volum og gjennomføring av restrukturering." },
  { n: "Union Pacific", t: "UNP", x: "NYSE · USA", i: "logistics", s: [6,8,5,6,5,6,8],
    r: ["AI brukes i drift og planlegging, men er lite profilert strategisk.",
        "Store sensor- og driftsdata fra et av Nord-Amerikas største jernbanenett.",
        "Begrenset bruk av digitale agenter utover kundeservice og planlegging.",
        "Automatiserte inspeksjonsportaler med maskinsyn og avanserte togstyringssystemer.",
        "Moderat intern kapasitet.",
        "Bransjeledende effektivitetsforbedringer (operating ratio) der teknologi bidrar.",
        "Sterk kontantstrøm; stor fusjon kan endre bildet."],
    th: "Stabil operatør med fysisk dataovertak – lav AI-profil.",
    rk: "Regulatorisk godkjenning og integrasjon ved fusjon." },
  { n: "A.P. Møller-Mærsk", t: "MAERSK B", x: "Nasdaq CPH · Danmark", i: "logistics", s: [6,7,6,5,6,5,8],
    r: ["Strategi om integrert ende-til-ende-logistikk med digitalisering, men AI er ikke kjernebudskapet.",
        "Global container- og havnedata, styrket av egne terminaler.",
        "AI i booking, kundeservice og dokumentasjon.",
        "Automatiserte containerterminaler via APM Terminals; datadrevet ruting av skip.",
        "Moderat intern kapasitet.",
        "Lite tallfestet effekt.",
        "Sterk balanse etter rekordår, men fraktrater svinger kraftig."],
    th: "Har dataene og terminalene – AI er ennå ikke i kjernen.",
    rk: "Fraktratesykluser og geopolitiske forstyrrelser i skipsruter." },
  { n: "DSV", t: "DSV", x: "Nasdaq CPH · Danmark", i: "logistics", s: [6,7,6,4,5,5,7],
    r: ["Effektivitets- og integrasjonsfokus; AI brukes som verktøy, ikke som strategi.",
        "Stor speditørdata, kraftig forsterket etter oppkjøpet av DB Schenker.",
        "AI i dokumenthåndtering, tollbehandling og prising av frakt.",
        "Moderat lagerautomasjon i kontraktslogistikk.",
        "Moderat; lean organisasjon med lite egen AI-forskning.",
        "Sterk historikk på kostnadssynergier, men AI-effekten er ikke isolert.",
        "Solid, men integrasjonen av Schenker binder kapital og ledelse."],
    th: "Integrasjon kan gi skalafordeler som gjør AI mer verdifullt.",
    rk: "Integrasjonsrisiko." },

  /* ---------------- TELEKOM & MEDIA ---------------- */
  { n: "T-Mobile US", t: "TMUS", x: "Nasdaq · USA", i: "telecom", s: [8,8,8,3,7,7,8],
    r: ["AI er sentralt i både kundeopplevelse og nettverk – høyt prioritert av ledelsen.",
        "Kunde-, bruks- og nettverksdata fra over 100 millioner kunder.",
        "Utviklet AI-drevet kundeserviceplattform sammen med OpenAI; agenter som løser saker proaktivt.",
        "AI-RAN-satsing med NVIDIA og andre for å gjøre radionettet til AI-infrastruktur.",
        "Partnerbasert, men med sterk intern produktkapasitet.",
        "Lavere churn og servicekostnader enn konkurrentene.",
        "Sterk kontantstrøm og vekst."],
    th: "Telekom-lederen på agentisk kundeservice.",
    rk: "Priskonkurranse i amerikansk mobilmarked." },
  { n: "Deutsche Telekom", t: "DTE", x: "XETRA · Tyskland", i: "telecom", s: [8,8,7,4,7,6,8],
    r: ["AI-strategi med tydelig europeisk suverenitetsprofil og ambisjon som AI-infrastrukturleverandør.",
        "Store kundedata i Europa og (via T-Mobile US) i USA.",
        "AI-agenter i kundeservice og nettdrift; samarbeid med flere AI-labber.",
        "Bygger industriell AI-sky med NVIDIA i Tyskland for europeisk industri og robotikk.",
        "Sterk intern kapasitet og egne AI-produkter.",
        "Effektivitetsgevinster kommunisert, men moderat dokumentert.",
        "Sterk balanse og kontantstrøm."],
    th: "Europas AI-infrastruktur-telekom.",
    rk: "Regulering og kapitalintensitet." },
  { n: "SoftBank Corp", t: "9434", x: "TSE · Japan", i: "telecom", s: [8,7,7,5,7,5,7],
    r: ["AI-infrastruktur og agenter er hjertet av strategien – tett koblet til morselskapets AI-satsing.",
        "Gode kunde- og betalingsdata i Japan (bl.a. via PayPay og LINE Yahoo).",
        "Agenter i kundeservice og internt; joint venture med OpenAI for agentløsninger i Japan.",
        "Bygger AI-datasentre og AI-RAN.",
        "Utvikler egne japanske språkmodeller.",
        "Tidlig; lite dokumentert finansiell effekt.",
        "Moderat – stor investering i datasentre."],
    th: "Japans AI-infrastruktur- og agentplattform.",
    rk: "Avhengig av morselskapet SoftBank Groups strategi og gjeld." },
  { n: "AT&T", t: "T", x: "NYSE · USA", i: "telecom", s: [7,8,7,2,7,6,7],
    r: ["AI brukes målrettet til kostnadskutt og bedre kundeservice.",
        "Store kunde- og nettverksdata i USA.",
        "Intern GenAI-plattform brukt av store deler av de ansatte og agenter i kundeservice og koding.",
        "Begrenset fysisk eksponering.",
        "Solid intern plattformkapasitet.",
        "Kommuniserte kostnadsbesparelser fra automasjon.",
        "Gjeldsbelastet, men med stabil kontantstrøm."],
    th: "Effektiviseringscase med god intern plattform.",
    rk: "Gjeld og lav vekst." },
  { n: "Telenor", t: "TEL", x: "Oslo Børs · Norge", i: "telecom", s: [7,6,6,3,6,5,6],
    r: ["Tydelig AI-ambisjon i Norden; har etablert egen AI-fabrikk i Norge.",
        "Kundedata i Norden og Asia, men fragmentert og i mindre skala.",
        "AI i kundeservice og nettdrift.",
        "AI-fabrikk med NVIDIA-infrastruktur for suveren AI i Norge.",
        "Moderat intern kapasitet.",
        "Tidlig, lite dokumentert.",
        "Moderat; stabil utbytteprofil begrenser investeringsrom."],
    th: "Nordisk suveren AI-infrastruktur – liten, men tidlig.",
    rk: "Lav vekst i kjernevirksomheten." },
  { n: "Verizon", t: "VZ", x: "NYSE · USA", i: "telecom", s: [6,8,6,2,6,5,6],
    r: ["AI brukes i kundeservice, men strategien er mindre tydelig enn hos konkurrentene.",
        "Store kundedata.",
        "GenAI-assistenter i kundeservice og salg.",
        "Begrenset fysisk eksponering.",
        "Moderat intern kapasitet.",
        "Begrenset dokumentert effekt.",
        "Gjeldsbelastet etter store oppkjøp."],
    th: "Følger i telekom-AI.",
    rk: "Konkurranse og gjeld." },

  /* ---------------- REISELIV & HOTELL ---------------- */
  { n: "Booking Holdings", t: "BKNG", x: "Nasdaq · USA", i: "travel", s: [8,9,8,1,8,7,9],
    r: ["Ledelsen har gjort «connected trip» med AI-agenter til sentral strategi.",
        "Enorm søke- og bookingdata for overnatting globalt – flest hotellpartnere i verden.",
        "AI-reiseplanlegger og agenter for kundeservice og partnere; integrert mot generelle AI-assistenter.",
        "Ingen vesentlig fysisk eksponering.",
        "Sterk ingeniørbase og datavitenskapsmiljø i Amsterdam.",
        "Lavere servicekostnader og bedre markedsføringseffektivitet rapportert.",
        "Sterk kontantstrøm og høy lønnsomhet."],
    th: "Best posisjonert reiseplattform for agentisk booking.",
    rk: "Generelle AI-assistenter kan flytte kunderelasjonen bort fra plattformene." },
  { n: "Trip.com Group", t: "TCOM", x: "Nasdaq/HKEX · Kina", i: "travel", s: [8,8,8,2,7,6,7],
    r: ["AI-assistenten TripGenie er sentral i produktstrategien.",
        "Sterke reise- og transportdata i Asia, inkludert tog og fly.",
        "AI-reiseassistent og AI i kundeservice i stor skala.",
        "Begrenset fysisk eksponering.",
        "Solid ingeniørbase i Kina.",
        "Effektivitetsgevinster i service, moderat dokumentert.",
        "Sterk vekst og god lønnsomhet."],
    th: "Asias AI-reiseplattform.",
    rk: "Geopolitikk og regulering i Kina." },
  { n: "Airbnb", t: "ABNB", x: "Nasdaq · USA", i: "travel", s: [8,8,8,1,9,6,9],
    r: ["CEO har gjort en AI-agent til kjernen i en ny app-strategi.",
        "Unike data om private utleiere, gjester og tillit/omdømme.",
        "AI-kundeserviceagent rullet ut i USA med færre saker som går til mennesker.",
        "Ingen vesentlig fysisk eksponering.",
        "Sterk ingeniørbase og aktiv AI-rekruttering.",
        "Tidlig dokumentasjon av effekt.",
        "Sterk kontantstrøm og netto kontantposisjon."],
    th: "Produktdrevet AI-omstilling med sterk merkevare.",
    rk: "Regulering av korttidsutleie." },
  { n: "Expedia Group", t: "EXPE", x: "Nasdaq · USA", i: "travel", s: [8,8,8,1,7,6,7],
    r: ["AI sentralt i både forbrukerprodukt og B2B-plattform.",
        "Store reisedata på tvers av fly, hotell og leiebil.",
        "AI-reiseassistent og tidlig integrasjon i ChatGPT og andre AI-assistenter.",
        "Ingen vesentlig fysisk eksponering.",
        "Solid ingeniørkapasitet etter plattformsamling.",
        "Moderat dokumentert effekt.",
        "Moderat."],
    th: "Tidlig ute med agentisk reise via tredjeparts AI-assistenter.",
    rk: "Konkurranse fra Booking og fra AI-assistentene selv." },
  { n: "Delta Air Lines", t: "DAL", x: "NYSE · USA", i: "travel", s: [7,8,6,4,6,6,6],
    r: ["AI brukes offensivt i prising og drift.",
        "Store kunde-, lojalitets- og driftsdata.",
        "AI-basert dynamisk prising og AI i kundeservice.",
        "Prediktivt vedlikehold av flyflåten.",
        "Partnerbasert.",
        "Prisingsgevinster rapportert på økende andel av billettene.",
        "Syklisk bransje med høy kapitalbinding."],
    th: "Flyselskapet som bruker AI mest offensivt.",
    rk: "Regulatorisk granskning av AI-basert prising." },
  { n: "Marriott International", t: "MAR", x: "Nasdaq · USA", i: "travel", s: [6,8,5,2,5,4,7],
    r: ["AI er del av en større teknologimodernisering, men ikke kjernen.",
        "Et av verdens største lojalitetsprogrammer gir rike kundedata.",
        "GenAI i søk, booking og service.",
        "Begrenset fysisk eksponering.",
        "Moderat intern kapasitet.",
        "Begrenset dokumentert effekt.",
        "Solid, kapitallett franchisemodell."],
    th: "Lojalitetsdata er hovedkortet i en agentisk verden.",
    rk: "AI-agenter kan flytte booking bort fra egne kanaler." },
  { n: "Hilton Worldwide", t: "HLT", x: "NYSE · USA", i: "travel", s: [6,7,5,2,5,4,7],
    r: ["AI i drift og kundeopplevelse, men lavere profil enn plattformene.",
        "Stort lojalitetsprogram.",
        "AI-assistenter for gjester og ansatte.",
        "Begrenset fysisk eksponering.",
        "Moderat intern kapasitet.",
        "Begrenset dokumentert effekt.",
        "Solid, kapitallett modell."],
    th: "Følger med solide data.",
    rk: "Disintermediering." }
];
